### ISSUE TITLE
Connect MySQL to Spring Boot

### ISSUE THREAD

**Issue by mrterranova** [Quaran-Team/server-EarthBnB#6]

**Comment by mohdarif8299** [comment]
Can I Work on this?

**Comment by mrterranova** [comment]
I actually have this up and running already. I just didn't close down the ticket. I thank you for your interest though.

**Comment by mrterranova** [comment]
first commit - went through as master branch due to no prior commits. However, Spring Boot initialized and attached to earthdb in mysql
